// Side-effect imports register each command
import './init.js'
import './create.js'
import './inspect.js'
import './validate.js'
import './export.js'
import './action.js'
import './summary.js'
import './teach.js'
import './extract.js'
import './mcp.js'
import './serve.js'
import './console.js'
import './help.js'
import './text-search.js'
